# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Peter Eisentraut
author: Peter Eisentraut
email: peter@eisentraut.org
description: >-
  Peter Eisentraut's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peter.eisentraut.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: petereisentraut
github_username:  petere
linkedin_username: petereisentraut

disqus:
  shortname: peter-eisentraut-org

google_analytics: UA-50941261-1

timezone: America/New_York

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title

feed:
  tags:
    only:
      - postgresql
